{% set name = "igorwriter" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/igorwriter-{{ version }}.tar.gz
  sha256: 8df17b7e880a4129d4958423402d65ef39f3102c1af8a43ba42602b83dfb7e22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - igorwriter
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/t-onoz/igorwriter
  summary: Write IGOR binary (.ibw) or text (.itx) files from numpy array
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - t-onoz
